### ISSUE TITLE
Active tab text is invisible

### ISSUE THREAD

**Issue by jacobwalkr** [idleberg/vscode-subway#1]
The file name on an active tab is white, which for most Subway themes is the same colour as (or very similar to) the background, as in this image:

![active tab label](https://cloud.githubusercontent.com/assets/2103207/23332235/429fb296-fb6e-11e6-815d-67ba527286a9.png)

I've had a poke around to see if I could fix it for myself, but I couldn't make head nor tail of it.

Cheers!

**Comment by idleberg** [comment]
Thanks for reporting. This will take some trial & error to find the cause. The themes are in plain TextMate format, where they only apply on the syntax, not on the rest of the window. Have some patience 😄

**Comment by jacobwalkr** [comment]
I'm glad it wasn't just me being thick! I'm sure there's a way, given that other themes seem to change the style of that tab, but I couldn't figure out the trick.

**Comment by idleberg** [comment]
The new version should have fixed that (the trick was to provide a base `uiTheme` in `package.json`)

**Comment by jacobwalkr** [comment]
Looks fixed to me! Nice one!
